### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_76#1]
pierwsze cwiczenie:
- [x] zaciagnij do repozytorium lokalnego zmiany, ktore zrobilem i zorientuj sie co sie zmienilo
- [x] domerguj lokalnie branch `test` do brancha `master`
- [x] wypchnij tak zmienionego brancha `master` do repozytorium zdalnego

**Comment by nescomtm** [comment]
zmieniłeś plik style.sass a dokładnie przeniosłeś @import przed clearfix()
dodałeś branch test i test w pliku style.sass sa zmiany

**Comment by nescomtm** [comment]
dograłem zmiany z gałęzi test do master plik style.sass linia 195 , wypchnołem zmieniona gałąź master na gita

**Comment by nescomtm** [comment]
mam uwagę do Kodilli, ze jak są święta takie jak były, to ten moduł powinien byc na 2 tygodnie a nie na tydzień ...
