### ISSUE TITLE
todo 2

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_76#2]
Kolejne kroki do zrobienia:
- [x] usun z repo wszystkie pliki bat (sa to Twoje pliki pomocnicze i nie sa czescia projektu). Dodaj ignorowanie tego typu plikow do pliku `.gitignore`. Potem mozesz na nowo dodac te pliki bat i git bedzie je juz ignorowal.
- [x] niepotrzebnie masz w folderze `css` dwa pliki css
- [x] sciagnij te 3 obrazki, ktore wykorzystujesz i laduj je lokalnie, po zmniejszeniu ich przez gruntowy task imagemin
- [x] nie moge uruchomic grunta na Twoim projekcie poniewaz nie moge zainstalowac zaleznosci (przez `npm install`), a to dlatego, ze brakuje Ci zdefiniowanych zaleznosci deweloperskich (devDependencies) dla taskow gruntowych w pliku `package.json`
- [x] dodaj do grunta task `watch`

**Comment by nescomtm** [comment]
mozna to sprawdzać

**Comment by zdolny** [comment]
- [x] pliki bat z folderu batch tez do usuniecia z repo
- [x] dodaj plik `.gitignore` z wpisem ignorowanych plikow

Nadal nie moge uruchomic Twojego projektu. Mozesz to przetestowac u siebie usuwajac folder `node_modules` i odpalajac komende `npm install`, a potem `grunt` - grunt powinien dzialac jesli wszystkie pluginy z `package.json` zostana zainstalowane

**Comment by nescomtm** [comment]
zrobione
